
CREATE TABLE date_dim (
    date_key datetime,
    Bank_Holiday_CY int,
    Bank_Holiday_UK int,
    CIGNA_Month_End int,
    cq_and_cy_name varchar(20),
    cq_name varchar(10),
    cy_name varchar(10),
    date_key_REAL datetime,
    day_cq_begin int,
    day_cq_end int,
    day_cy_begin int,
    day_cy_end int,
    day_fq_begin int,
    day_fq_end int,
    day_fy_begin int,
    day_fy_end int,
    day_month_begin int,
    day_month_end int,
    day_name datetime,
    day_number_in_cq int,
    day_number_in_cy int,
    day_number_in_fq int,
    day_number_in_fy int,
    day_number_in_month int,
    day_number_in_week int,
    day_number_til_end_cq int,
    day_number_til_end_fq int,
    fq_and_fy_name varchar(20),
    fq_name varchar(10),
    fy_name varchar(10),
    julian_counter int,
    month_and_cy_name varchar(8),
    month_and_fy_name varchar(8),
    month_name varchar(8),
    month_number int,
    month_number_in_cq int,
    month_number_in_cy int,
    month_number_in_fq int,
    month_number_in_fy int,
    month_number_til_end_cy int,
    month_number_til_end_fy int,
    vacation_day int,
    week_friday datetime,
    week_monday datetime,
    week_number int,
    week_number_cq int,
    week_number_cy int,
    week_number_fq int,
    week_number_fy int,
    week_number_til_end_cq int,
    week_number_til_end_cy int,
    week_number_til_end_fq int,
    week_number_til_end_fy int,
    week_saturday datetime,
    week_sunday datetime,
    weekdays varchar(3),
    Weekend_Working_Day_CY int,
    Working_Day_Counter_CY int,
    Working_Day_Counter_UK int,
    Working_Day_CY int,
    Working_Day_UK int
);
WITH DateSeries AS (
    SELECT CAST('2000-01-01' AS datetime) AS date_key
    UNION ALL
    SELECT date_key + 1
    FROM DateSeries
    WHERE date_key + 1 <= '2050-12-31'
)
INSERT INTO date_dim 
(
    date_key, 
	Bank_Holiday_CY, 
	Bank_Holiday_UK, 
	CIGNA_Month_End, 
	cq_and_cy_name, 
	cq_name, 
	cy_name, 
    date_key_REAL, 
	day_cq_begin, 
	day_cq_end, 
	day_cy_begin, 
	day_cy_end, 
	day_fq_begin, 
	day_fq_end, 
    day_fy_begin, 
	day_fy_end, 
	day_month_begin, 
	day_month_end, 
	day_name, 
	day_number_in_cq, 
	day_number_in_cy, 
    day_number_in_fq, 
	day_number_in_fy, 
	day_number_in_month, 
	day_number_in_week, 
	day_number_til_end_cq, 
    day_number_til_end_fq, 
	fq_and_fy_name, 
	fq_name, fy_name, 
	julian_counter, 
	month_and_cy_name, 
    month_and_fy_name, 
	month_name, 
	month_number, 
	month_number_in_cq, 
	month_number_in_cy, 
	month_number_in_fq, 
    month_number_in_fy, 
	month_number_til_end_cy, 
	month_number_til_end_fy, 
	vacation_day, week_friday, 
    week_monday, week_number, 
	week_number_cq, week_number_cy, 
	week_number_fq, week_number_fy, 
    week_number_til_end_cq, 
	week_number_til_end_cy, 
	week_number_til_end_fq, 
	week_number_til_end_fy, 
    week_saturday, week_sunday, 
	weekdays, Weekend_Working_Day_CY, 
	Working_Day_Counter_CY, 
    Working_Day_Counter_UK, 
	Working_Day_CY, 
	Working_Day_UK
)
SELECT 
    date_key, 
    0 AS Bank_Holiday_CY,
    0 AS Bank_Holiday_UK,
    0 AS CIGNA_Month_End,
    'Q1 2022' AS cq_and_cy_name,
    'Q1' AS cq_name,
    '2022' AS cy_name,
    date_key AS date_key_REAL,
    1 AS day_cq_begin,
    0 AS day_cq_end,
    1 AS day_cy_begin,
    0 AS day_cy_end,
    1 AS day_fq_begin,
    0 AS day_fq_end,
    1 AS day_fy_begin,
    0 AS day_fy_end,
    1 AS day_month_begin,
    0 AS day_month_end,
    date_key AS day_name,
    DATEDIFF(DAY, '2022-01-01', date_key) + 1 AS day_number_in_cq,
    DATEDIFF(DAY, '2022-01-01', date_key) + 1 AS day_number_in_cy,
    DATEDIFF(DAY, '2022-01-01', date_key) + 1 AS day_number_in_fq,
    DATEDIFF(DAY, '2022-01-01', date_key) + 1 AS day_number_in_fy,
    DAY(date_key) AS day_number_in_month,
    DATEPART(WEEKDAY, date_key) AS day_number_in_week,
    90 - DATEDIFF(DAY, date_key, '2022-03-31') AS day_number_til_end_cq,
    90 - DATEDIFF(DAY, date_key, '2022-03-31') AS day_number_til_end_fq,
    'Q1 2022' AS fq_and_fy_name,
    'Q1' AS fq_name,
    '2022' AS fy_name,
    44196 AS julian_counter,
    FORMAT(date_key, 'MMM-yyyy') AS month_and_cy_name,
    FORMAT(date_key, 'MMM-yyyy') AS month_and_fy_name, -- Updated this part to correctly format it
    FORMAT(date_key, 'MMM') AS month_name,
    MONTH(date_key) AS month_number,
    DAY(date_key) AS month_number_in_cq,
    MONTH(date_key) AS month_number_in_cy,
    MONTH(date_key) AS month_number_in_fq,
    MONTH(date_key) AS month_number_in_fy,
    12 - MONTH(date_key) AS month_number_til_end_cy,
    12 - MONTH(date_key) AS month_number_til_end_fy,
    0 AS vacation_day,
    date_key - DAY(date_key) + 5 AS week_friday,
    date_key - DAY(date_key) + 1 AS week_monday,
    DATEPART(WEEK, date_key) AS week_number,
    DATEDIFF(WEEK, '2022-01-01', date_key) + 1 AS week_number_cq,
    DATEDIFF(WEEK, '2022-01-01', date_key) + 1 AS week_number_cy,
    DATEDIFF(WEEK, '2022-01-01', date_key) + 1 AS week_number_fq,
    DATEDIFF(WEEK, '2022-01-01', date_key) + 1 AS week_number_fy,
    53 - DATEDIFF(WEEK, date_key, '2022-12-31') AS week_number_til_end_cq,
    53 - DATEDIFF(WEEK, date_key, '2022-12-31') AS week_number_til_end_cy,
    53 - DATEDIFF(WEEK, date_key, '2022-12-31') AS week_number_til_end_fq,
    53 - DATEDIFF(WEEK, date_key, '2022-12-31') AS week_number_til_end_fy,
    date_key - DAY(date_key) + 6 AS week_saturday,
    date_key - DAY(date_key) AS week_sunday,
    CASE WHEN DATEPART(WEEKDAY, date_key) = 7 THEN 'Sat' ELSE 'Sun' END AS weekdays,
    0 AS Weekend_Working_Day_CY,
    31438 AS Working_Day_Counter_CY,
    31433 AS Working_Day_Counter_UK,
    0 AS Working_Day_CY,
    0 AS Working_Day_UK
FROM DateSeries
OPTION (MAXRECURSION 0);

select * from date_dim 

---to find no of columns in table---
SELECT count(*) as No_of_Column FROM information_schema.columns WHERE table_name ='date_dim' 

truncate table date_dim